// import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Poppins } from "next/font/google";
import Urlheader from "@/Components/header";
import Urlfooter from "@/app/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "700"], // Choose the weights you need
  variable: "--font-poppins", // Optional: use CSS variable
});

export const metadata = {
  title: "URL Shortener",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className={`w-full ${poppins.variable}}`}>
          <Urlheader />
        {children}
        {/* <Urlfooter /> */}
      </body>
    </html>
  );
}
